# Generated by Django 4.0.6 on 2022-07-25 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
        ('models', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='projects',
            field=models.ManyToManyField(to='projects.project'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='appinstance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='apps.appinstance'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='projects',
            field=models.ManyToManyField(to='projects.project'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinstance', to='apps.apps'),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='app_dependencies',
            field=models.ManyToManyField(blank=True, to='apps.appinstance'),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='model_dependencies',
            field=models.ManyToManyField(blank=True, to='models.model'),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinstance', to='projects.project'),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='apps.tagulous_appinstance_tags'),
        ),
        migrations.AlterUniqueTogether(
            name='apps',
            unique_together={('slug', 'revision')},
        ),
    ]
